### ISSUE TITLE
How does the downsampleSFS function work?

### ISSUE THREAD

**Issue by sagitaninta** [isinaltinkaya/WPSG2022#2]
Hi there,

I came across this GitHub page while browsing [the Evomics workshop schedule](http://evomics.org/2022-workshop-on-population-and-speciation-genomics-cesky-krumlov/) and really curious about this downsampling SFS function here you got on [Exercise 3](https://github.com/isinaltinkaya/WPSG2022/blob/main/fst_pbs.md):

```
#due the very limited amount of sites
#downsample to 5 individuals (10 chromosome) and exclude fixed derived
downsampleSFS <- function(x,chr){ #x 1:2n , chr < 2n
    n<-length(x)
    mat <- sapply(1:chr,function(i) choose(1:n,i)*choose(n-(1:n),chr-i)/choose(n,chr))
    nnorm( as.vector(t(mat) %*% x)[-chr] )
}
```

Could you explain what happened there? How does the downsampling actually happen from series of numbers of sites? I have tried to illustrate things myself but not sure.

**Comment by ANGSD** [comment]
It is described in this paper: https://pubmed.ncbi.nlm.nih.gov/20558595/ <https://pubmed.ncbi.nlm.nih.gov/20558595/>

Best
Thorfinn
